name: Build APK DNS-SEC 2026
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Verificar archivos presentes
        run: ls -R  # Esto nos mostrará en el log si el archivo existe

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Buildozer y Dependencias
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Compilar APK con Buildozer
        run: |
          # Forzamos la aceptación de licencias y la búsqueda del archivo
          yes | buildozer android debug
        
      - name: Subir APK Generada
        uses: actions/upload-artifact@v4
        with:
          name: DNS-SEC-Instalable-Javic888
          path: bin/*.apk
          
